version: '3.8'

services:
  nodejs-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4321:4321"
    environment:
      - NODE_ENV=production
      - MONGODB_URL=mongodb://mongodb:27017/ReservationSalle
    networks:
      - app-network
    depends_on:
      - mongodb

  mongodb:
    image: mongo:4.4.6   # Utiliser une version compatible avec votre système
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
