
#FROM node:20.5


#WORKDIR /usr/src/app


#COPY package*.json ./


#RUN npm install --production

# Copy local code to the container image.
#COPY . .

# Run the web service on container startup.
#CMD [ "node", "server.js" ]

# Expose the port the app runs on.
#EXPOSE 4321
